apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rocketchat
  labels:
    app: rocketchat-web
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat-web
  template:
    metadata:
      labels:
        app: rocketchat-web
    spec:
      containers:
        - name: rocketchat-web
          image: rocketchat/rocket.chat:latest
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: ROOT_URL
              value: "https://rocketchat.tycho.cloud"
            - name: MONGO_URL
              value: "mongodb://rocketchat-database:27017/rocketchat"
          livenessProbe:
            httpGet:
              path: /api/info
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
          volumeMounts:
            - name: rocket-data
              mountPath: /app/uploads
      volumes:
        - name: rocket-data
          persistentVolumeClaim:
            claimName: rocketchat-web-pvc
