version: '3'
services:
  rocketchat:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:3000
    environment:
      - ROOT_URL=http://localhost
    depends_on:
      - db
  db:
    image: mongo:4.0
